version: '1.0'
mode: parallel
stages:
- prep
- push

steps:
  clang_7_prep: &prep
    type: build
    stage: prep
    title: Prep test image clang-7
    dockerfile: Dockerfile-clang
    build_arguments:
    - CLANG_VERSION=7
    - CMAKE_VERSION=3.14.0
    image_name: ${{CF_REPO_OWNER}}/clang-cmake
    tag: 7_cmake-3.14.0
    when:
      steps:
      - name: main_clone
        on:
        - success

  clang_7_push: &push
    type: push
    stage: push
    title: Push clang-7 to DockerHub
    candidate: ${{clang_7_prep}}
    image_name: ${{CF_REPO_OWNER}}/clang-cmake
    tags: 
    - '7_cmake-3.14.0'
    - '7_cmake-3.14'
    - '7_cmake-3'
    - '7'
    registry: dockerhub
    when:
      steps:
      - name: clang_7_prep
        on:
        - success

  clang_6_prep:
    <<: *prep
    title: Prep test image clang-6
    build_arguments:
    - CLANG_VERSION=6.0
    - CMAKE_VERSION=3.14.0
    tag: 6_cmake-3.14.0

  clang_6_push:
    <<: *push
    title: Push clang-6 to DockerHub
    candidate: ${{clang_6_prep}}
    tags: 
    - '6_cmake-3.14.0'
    - '6_cmake-3.14'
    - '6_cmake-3'
    - '6'
    when:
      steps:
      - name: clang_6_prep
        on:
        - success

  clang_5_prep:
    <<: *prep
    title: Prep test image clang-5
    build_arguments:
    - CLANG_VERSION=5.0
    - CMAKE_VERSION=3.14.0
    tag: 5_cmake-3.14.0

  clang_5_push:
    <<: *push
    title: Push clang-5 to DockerHub
    candidate: ${{clang_5_prep}}
    tags: 
    - '5_cmake-3.14.0'
    - '5_cmake-3.14'
    - '5_cmake-3'
    - '5'
    when:
      steps:
      - name: clang_5_prep
        on:
        - success

  clang_4_prep:
    <<: *prep
    title: Prep test image clang-4
    build_arguments:
    - CLANG_VERSION=4.0
    - CMAKE_VERSION=3.14.0
    tag: 4_cmake-3.14.0

  clang_4_push:
    <<: *push
    title: Push clang-4 to DockerHub
    candidate: ${{clang_4_prep}}
    tags: 
    - '4_cmake-3.14.0'
    - '4_cmake-3.14'
    - '4_cmake-3'
    - '4'
    when:
      steps:
      - name: clang_4_prep
        on:
        - success

  clang_3_9_prep:
    <<: *prep
    title: Prep test image clang-3.9
    build_arguments:
    - CLANG_VERSION=3.9
    - CMAKE_VERSION=3.14.0
    tag: 3.9_cmake-3.14.0

  clang_3_9_push:
    <<: *push
    title: Push clang-3.9 to DockerHub
    candidate: ${{clang_3_9_prep}}
    tags: 
    - '3.9_cmake-3.14.0'
    - '3.9_cmake-3.14'
    - '3.9_cmake-3'
    - '3.9'
    when:
      steps:
      - name: clang_3_9_prep
        on:
        - success

  clang_3_8_prep:
    <<: *prep
    title: Prep test image clang-3.8
    build_arguments:
    - CLANG_VERSION=3.8
    - CMAKE_VERSION=3.14.0
    tag: 3.8_cmake-3.14.0

  clang_3_8_push:
    <<: *push
    title: Push clang-3.8 to DockerHub
    candidate: ${{clang_3_8_prep}}
    tags: 
    - '3.8_cmake-3.14.0'
    - '3.8_cmake-3.14'
    - '3.8_cmake-3'
    - '3.8'
    when:
      steps:
      - name: clang_3_8_prep
        on:
        - success

  clang_3_7_prep:
    <<: *prep
    title: Prep test image clang-3.7
    build_arguments:
    - CLANG_VERSION=3.7
    - CMAKE_VERSION=3.14.0
    tag: 3.7_cmake-3.14.0

  clang_3_7_push:
    <<: *push
    title: Push clang-3.7 to DockerHub
    candidate: ${{clang_3_7_prep}}
    tags: 
    - '3.7_cmake-3.14.0'
    - '3.7_cmake-3.14'
    - '3.7_cmake-3'
    - '3.7'
    when:
      steps:
      - name: clang_3_7_prep
        on:
        - success

  clang_3_6_prep:
    <<: *prep
    title: Prep test image clang-3.6
    build_arguments:
    - CLANG_VERSION=3.6
    - CMAKE_VERSION=3.14.0
    tag: 3.6_cmake-3.14.0

  clang_3_6_push:
    <<: *push
    title: Push clang-3.6 to DockerHub
    candidate: ${{clang_3_6_prep}}
    tags: 
    - '3.6_cmake-3.14.0'
    - '3.6_cmake-3.14'
    - '3.6_cmake-3'
    - '3.6'
    when:
      steps:
      - name: clang_3_6_prep
        on:
        - success
